Feature/7 bd repository
oa-ek/lab-1-beavers pull request #6
Opened 2023-09-15 19:11 UTC by WhiteSenat0r

Created repository for the database, removed redundant usings

2023-09-15 19:42 UTC, IcticStep requested changes

2023-09-15 19:42 UTC, IcticStep commented on Infrastructure/Repository/GenericRepository.cs
> +        await Context.Set<TEntity>().ToListAsync();
Move async/await state machine higher.

2023-09-15 19:42 UTC, IcticStep commented on Infrastructure/Repository/GenericRepository.cs
> +        (await Context.Set<TEntity>().SingleOrDefaultAsync())!;
Move async/await state machine higher.

2023-09-15 19:42 UTC, IcticStep commented on Infrastructure/Repository/GenericRepository.cs
> +    public virtual void RemoveExistingEntity(TEntity removedEntity)
Why virtual?

2023-09-15 19:42 UTC, IcticStep commented on Infrastructure/Repository/GenericRepository.cs
> +    private ApplicationContext Context { get; init; }
Change to readonly field.

2023-09-15 19:56 UTC, WhiteSenat0r commented
Fixed mentioned issues in a new commit.

2023-09-16 10:49 UTC, IcticStep approved these changes

2023-09-16 10:49 UTC, IcticStep commented on Infrastructure/Repository/GenericRepository.cs
>      protected GenericRepository(ApplicationContext dbContext) =>
Constructor should be after properties.

2023-09-16 12:17 UTC, merged